//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividade
    {
        public Actividade()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int id { get; set; }
        public string actividad_desc { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
