//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja_Ahorro
    {
        public int pre_id { get; set; }
        public string pre_nombre { get; set; }
        public string pre_matricula { get; set; }
        public string pre_adscripcioon { get; set; }
        public string pre_tarjeta_cuenta { get; set; }
        public string pre_banco { get; set; }
        public string pre_telefono { get; set; }
        public string pre_recibo { get; set; }
        public string pre_ine { get; set; }
        public string pre_cantidad { get; set; }
        public System.DateTime pre_fecha { get; set; }
        public string pre_tipo { get; set; }
        public string pre_estatus { get; set; }
    }
}
