//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAlumnos
    {
        public int alum_id { get; set; }
        public string alum_nombre { get; set; }
        public string alum_paterno { get; set; }
        public string alum_materno { get; set; }
        public System.DateTime alum_f_nacimiento { get; set; }
        public string alum_curp { get; set; }
        public int alum_semestre { get; set; }
        public string alum_grupo { get; set; }
        public string alum_afiliacion_imss { get; set; }
        public string alum_tipo_sangre { get; set; }
        public string alum_especialidad { get; set; }
        public string alum_generacion { get; set; }
        public string alum_matricula { get; set; }
        public string alum_calle { get; set; }
        public string alum_num_ext { get; set; }
        public string alum_num_int { get; set; }
        public string alum_colonia { get; set; }
        public string alum_estado { get; set; }
        public string alum_municipio { get; set; }
        public string alum_ciudad { get; set; }
        public string alum_cp { get; set; }
        public string alum_tel_emergencia { get; set; }
        public string alum_cel_alumno { get; set; }
        public string alum_email { get; set; }
        public string alum_alergia { get; set; }
        public string alum_alergia_descrip { get; set; }
        public string alum_discapacidad { get; set; }
        public string alum_discapacidad_descrip { get; set; }
        public string alum_tratamiento { get; set; }
        public string alum_tratamiento_descrip { get; set; }
        public Nullable<int> alum_responsable_id { get; set; }
    }
}
