//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Plazas
    {
        public int catp_id { get; set; }
        public string catp_descrip { get; set; }
        public string catp_status { get; set; }
        public string catp_u_captura { get; set; }
        public System.DateTime catp_f_captura { get; set; }
        public string catp_categoria { get; set; }
        public string catp_funcion { get; set; }
        public string catp_adscripcion { get; set; }
    }
}
