//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactanos
    {
        public int con_id { get; set; }
        public string con_concepto { get; set; }
        public string con_texto { get; set; }
        public string con_link { get; set; }
        public string con_visible { get; set; }
    }
}
