//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CResponsable
    {
        public int resp_id { get; set; }
        public string resp_nombre { get; set; }
        public string resp_paterno { get; set; }
        public string resp_materno { get; set; }
        public string resp_parentesco { get; set; }
        public string resp_ocupacion { get; set; }
        public string resp_calle { get; set; }
        public string resp_num_ext { get; set; }
        public string resp_num_int { get; set; }
        public string resp_colonia { get; set; }
        public string resp_estado { get; set; }
        public string resp_municipio { get; set; }
        public string resp_ciudad { get; set; }
        public string resp_cp { get; set; }
        public string resp_tel_casa { get; set; }
        public string resp_cel_responsable { get; set; }
        public string resp_tel_trabajo { get; set; }
        public string resp_horario { get; set; }
        public string resp_email { get; set; }
    }
}
