//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descarga_Archivos
    {
        public int da_id { get; set; }
        public string da_descripcion { get; set; }
        public string da_matricula { get; set; }
        public string da_nombre { get; set; }
        public System.DateTime da_fecha { get; set; }
    }
}
