//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria
    {
        public int gal_id { get; set; }
        public string gal_titulo { get; set; }
        public string gal_ruta { get; set; }
        public string gal_u_publica { get; set; }
        public System.DateTime gal_f_publica { get; set; }
        public string gal_cancela { get; set; }
    }
}
