//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integrantes
    {
        public int int_id { get; set; }
        public string int_nombre { get; set; }
        public string int_puesto { get; set; }
        public string int_ruta_imagen { get; set; }
        public string int_cancelado { get; set; }
        public string int_class { get; set; }
        public Nullable<int> int_orden { get; set; }
    }
}
