//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int menu_id { get; set; }
        public string menu_descrip { get; set; }
        public int menu_orden { get; set; }
        public string menu_cancelar { get; set; }
        public string menu_routerLink { get; set; }
    }
}
