//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicaciones
    {
        public int pub_id { get; set; }
        public string pub_titulo { get; set; }
        public string pub_subtitulo { get; set; }
        public string pub_texto { get; set; }
        public string pub_u_publica { get; set; }
        public System.DateTime pub_f_publica { get; set; }
        public string pub_cancela { get; set; }
        public int pub_id_categoria { get; set; }
        public string pub_ruta { get; set; }
    
        public virtual Pub_Categoria Pub_Categoria { get; set; }
    }
}
