//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class steujedo_sindicatoEntities : DbContext
    {
        public steujedo_sindicatoEntities()
            : base("name=steujedo_sindicatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actividade> Actividades { get; set; }
        public DbSet<Lista_Asistencia> Lista_Asistencia { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Ure> Ures { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Archivo> Archivos { get; set; }
        public DbSet<Usuarios_Base> Usuarios_Base { get; set; }
        public DbSet<Integrante> Integrantes { get; set; }
        public DbSet<Pub_Categoria> Pub_Categoria { get; set; }
        public DbSet<Publicacione> Publicaciones { get; set; }
        public DbSet<Perfil> Perfils { get; set; }
        public DbSet<Contactano> Contactanos { get; set; }
        public DbSet<Audioteca> Audiotecas { get; set; }
    }
}
