//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class steujedo_sindicatoEntities : DbContext
    {
        public steujedo_sindicatoEntities()
            : base("name=steujedo_sindicatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actividades> Actividades { get; set; }
        public DbSet<Archivos> Archivos { get; set; }
        public DbSet<Audioteca> Audioteca { get; set; }
        public DbSet<Caja_Ahorro> Caja_Ahorro { get; set; }
        public DbSet<CAlumnos> CAlumnos { get; set; }
        public DbSet<Cat_Plazas> Cat_Plazas { get; set; }
        public DbSet<Cat_Servicios> Cat_Servicios { get; set; }
        public DbSet<Concurso_Plazas> Concurso_Plazas { get; set; }
        public DbSet<Contactanos> Contactanos { get; set; }
        public DbSet<CResponsable> CResponsable { get; set; }
        public DbSet<Descarga_Archivos> Descarga_Archivos { get; set; }
        public DbSet<Galeria> Galeria { get; set; }
        public DbSet<Integrantes> Integrantes { get; set; }
        public DbSet<Lista_Asistencia> Lista_Asistencia { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Padron_advo> Padron_advo { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<Pre_Revolvente> Pre_Revolvente { get; set; }
        public DbSet<Pub_Categoria> Pub_Categoria { get; set; }
        public DbSet<Publicaciones> Publicaciones { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Transparencia> Transparencia { get; set; }
        public DbSet<Ures> Ures { get; set; }
        public DbSet<User_Base> User_Base { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Videos_FL> Videos_FL { get; set; }
        public DbSet<concurso_antig> concurso_antig { get; set; }
        public DbSet<Comite_Ejecutivo> Comite_Ejecutivo { get; set; }
    }
}
