//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transparencia
    {
        public int tr_archivo_id { get; set; }
        public string tr_archivo_descrip { get; set; }
        public string tr_archivo_ruta { get; set; }
        public string tr_archivo_cancela { get; set; }
    }
}
