//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Base
    {
        public int ub_id { get; set; }
        public string ub_user { get; set; }
        public string ub_nombre { get; set; }
        public string ub_password { get; set; }
        public string ub_curp { get; set; }
        public string ub_rfc { get; set; }
    }
}
