//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos_FL
    {
        public int vid_id { get; set; }
        public string vid_titulo { get; set; }
        public int vid_ancho { get; set; }
        public int vid_largo { get; set; }
        public string vid_src { get; set; }
        public string vid_u_publica { get; set; }
        public System.DateTime vid_f_publica { get; set; }
    }
}
